spring:
  datasource:
    url: jdbc:h2:mem:expense-tracker-system
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: '/console'

flyway:
  baselineOnMigrate: true